export { default as PointsMainPage } from "./pointsMain.page";
export { default as MissionsPage } from "./missions.page";
export { default as GiftsPage } from "./gifts.page";
export { default as RequestPage } from "./request.page";
export { default as RolesPage } from "./roles.page";
export { default as PrivilegesPage } from "./Privileges.page";
export { default as RewardsMainPage } from "./rewardsMain.page";
export { default as Rewards } from "./Rewards";
export { default as CrowdPointsPage } from "./crowdpoints.page";
